### ISSUE TITLE
DatePicker Warnings

### ISSUE THREAD

**Issue by PhilipGrey** [zhDmitry/redux-form-antd#13]
Upon clicking the datepicker input, I get the following warnings:

Failed prop type: Invalid prop `value` supplied to `Picker`.
and
Failed prop type: Invalid prop `selectedValue` of type `string` supplied to `Calendar`, expected `object`.

The input still works, it's just throwing these warnings.

**Comment by zhDmitry** [comment]
It is strange because there is formatter from string to moment format. This error only could be if you pass "" as value props.

**Comment by PhilipGrey** [comment]
What would be passed in for an empty value?

**Comment by PhilipGrey** [comment]
Very similar to the issue these guys are having: https://github.com/erikras/redux-form-material-ui/issues/37

**Comment by zhDmitry** [comment]
It seems that default value should be null instead of empty string, but it needs to be tested. I will fix it on days. If you want sooner you can make pull request.
