### ISSUE TITLE
ANTD v3

### ISSUE THREAD

**Issue by luispeerez** [zhDmitry/redux-form-antd#15]
Hi, first of all, what a great tool, this helped me a lot with antd components and the redux-form implementation I am working on.

I just wanted to know if there are plans to change the antd dependency version to the latest ( I think is 3.1.6 at the moment)

**Comment by zhDmitry** [comment]
Yeah, it is possible, but currently I don't have a lot of time for working on this project. Could you made such changes and publish them to gh-pages, smth like that 'https://zhdmitry.github.io/redux-form-antd/' if all components will be ok I will release new version of this component.

**Comment by luispeerez** [comment]
I placed it here https://luispeerez.github.io/redux-form-antd/ if you think they work correctly I think it will be ok to do the upgrade. 
It is using
antd: 3.2.0
redux-form: 7.2.3

**Comment by zhDmitry** [comment]
Looks nice.  Please make your pull request.

**Comment by luispeerez** [comment]
#18
