### ISSUE TITLE
Select component not rendering ok

### ISSUE THREAD

**Issue by luispeerez** [zhDmitry/redux-form-antd#16]
![screenshot from 2018-02-02 13 25 48](https://user-images.githubusercontent.com/3952671/35748613-9b393f9c-081c-11e8-8aef-b04dadf46485.png)
Hi, I have this weird case using the SelectField component, when I place it like above, the Select component renders without some style properties
``          <Field 
            name="test" 
            label="Test" 
            mode="default"
            component={SelectField} 
            options={options}
          >
          </Field>
``

Then when I declare Option in my code like this:
``
import { Select} from 'antd';
const Option = Select.Option;
``
The Select component renders with the proper styles.

In my project I am using antd v 3.0.3 .I'm thinking that it may be a case where the Option I am declaring styles correctly the SelectField component (that is why I opened this issue/question https://github.com/zhDmitry/redux-form-antd/issues/15 )
![screenshot from 2018-02-02 13 07 19](https://user-images.githubusercontent.com/3952671/35748585-805da064-081c-11e8-825e-f9018ce6513a.png)

**Comment by luispeerez** [comment]
with a fork of redux-form-antd (https://github.com/luispeerez/redux-form-antd/) using the latest version of  antd and redux-form this problem doesn't appear anymore. Without the need of declaring

`import { Select} from 'antd'; `
`const Option = Select.Option;`


![screenshot from 2018-02-07 20 07 05](https://user-images.githubusercontent.com/3952671/35950719-dc71b6a6-0c45-11e8-8493-b1d072976894.png)

**Comment by Geczy** [comment]
https://github.com/zhDmitry/redux-form-antd/issues/30
