### ISSUE TITLE
SelectField multiple - defaultValues doesn't work

### ISSUE THREAD

**Issue by jirikomon** [zhDmitry/redux-form-antd#17]
Hi,
just found out that `defaultValues` is literally ignored on Select in mode "multiple". Problem seems to be in this redux-form binding wrapper. When native Select component from antd used, default values works just fine.

I understand that you don't have much of a spare time to deal with these issues, but I thought keeping bug tracked is a good thing anyways.

**Comment by luispeerez** [comment]
why dont you set initialValues on reduxForm config? I think it could be cleaner using the reduxForm api to set the values https://redux-form.com/7.2.3/docs/api/reduxform.md/#-code-initialvalues-object-lt-string-string-gt-code-optional-

**Comment by jirikomon** [comment]
Turned out I had initialValues for that select set to empty array deep down in component, away of handling logic. My bad, multiselect works just fine.
