### ISSUE TITLE
Radio Buttion

### ISSUE THREAD

**Issue by deliriousrhino** [zhDmitry/redux-form-antd#19]
Looking at the code I believe I should be able to use ants RadioButton by passing in button but it does not work
```
<Field name="public" component={RadioField} hinttext="Name" button options={[
            {
              "label": "Public!",
              "value": true
            },
            {
              "label": "Draft",
              "value": false
            }
          ]}/>
```
Is still rendered as a normal radio group.

How can I set the Field to use RadioButtons?

Thank You!

**Comment by zhDmitry** [comment]
![image](https://user-images.githubusercontent.com/14317641/36142552-1e044cc2-10b1-11e8-8d05-3a2760b5570f.png)
you should pass prop button={true} to render radiobutton
