### ISSUE TITLE
Set datepicker default to null instead of today date

### ISSUE THREAD

**Issue by stefensuhat** [zhDmitry/redux-form-antd#2]
Hi,

Thanks for the package. Is there any chance to make the datepicker default value empty instead of today's date?

The problem with it is, even though the datepicker has today value when submitting redux form will detect it as empty value.

**Comment by stefensuhat** [comment]
I PR about this.

maybe you can check it out?
Thanks

**Comment by zhDmitry** [comment]
Done. Thanks for pr.
