### ISSUE TITLE
You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

### ISSUE THREAD

**Issue by juanpmarin** [zhDmitry/redux-form-antd#24]
Hi,
Currently the library is raising that warning, I think it is because of the import on index.js
```
import { Checkbox, Input, Slider, InputNumber, Switch } from "antd";
```
instead of that it should be
```
import Checkbox from 'antd/lib/checkbox';
import Input from 'antd/lib/input';
...etc
```

**Comment by zhDmitry** [comment]
it would be great if you crate pr for such improvement )

**Comment by mrwillis** [comment]
This doesn't seem inline with the recommendation in the documentation. It's suggesting now that you use `babel-plugin-import` and import the named exports from the index as in the first example. I think now the first way is more correct.
