### ISSUE TITLE
Export createComponent and customMap to create custom wrapped components

### ISSUE THREAD

**Issue by ScriptWorker** [zhDmitry/redux-form-antd#28]
Hello Dmitry,

It is a feature request to have possibility to create bindings for custom components.
For example we have custom component based on Ant's Input.Search. It would be great if redux-form-antd will expose functions to wrap such components with bindings, so we would be able to use it as redux-form-antd provided components.

To achieve this createComponent and customMap functions should be exported. What do you think about it?

**Comment by zhDmitry** [comment]
Hi it would be nice.  But currently i don't have any possibility to test such enhancement on real project. So it welcome to make pr.

**Comment by ScriptWorker** [comment]
Hi Dmitriy, thank you for your response and for merging the PR. When are you going to publish the npm package?
Also I can see a version mismatch. In package.json there is a 1.0.3, while already published npm package has 1.0.4.

**Comment by zhDmitry** [comment]
Hi, thanks for your pr, i will publish it in next Monday. Now i don't have any ability to publish it (

**Comment by ScriptWorker** [comment]
Thank you.
