### ISSUE TITLE
FormItem is not defined

### ISSUE THREAD

**Issue by stefensuhat** [zhDmitry/redux-form-antd#4]
```
D:\www\example\dashboard\node_modules\redux-form-antd\lib\components\BaseComponent.js:56 Uncaught ReferenceError: FormItem is not defined
    at InputComponent.render (D:\www\example\dashboard\node_modules\redux-form-antd\lib\components\BaseComponent.js:56)
```

**Comment by stefensuhat** [comment]
I've made a PR for this

**Comment by matepaiva** [comment]
If the PR was not accepted, why is this issue closed?

**Comment by zhDmitry** [comment]
Check this file. All is fine.
https://github.com/zhDmitry/redux-form-antd/blob/master/src/components/BaseComponent.js.
I have made this fix with another bunch of changes so pull request became obsolete.
