### ISSUE TITLE
validation icon is misplaced with select component

### ISSUE THREAD

**Issue by RomaSto** [zhDmitry/redux-form-antd#41]
I am trying to add select and validate it:
        <Field
          label="Role"
          name="role"
          type="text"
          component={SelectField}
          placeholder="Select a role"
          options={[
            { label: 'ADMIN', value: 'ADMIN' },
            { label: 'EMPLOYEE', value: 'EMPLOYEE' },
            { label: 'USER', value: 'USER' }
          ]}
        validate={[required]}
        />

here is what I get
https://drive.google.com/open?id=1gex1HzvtNMogQj238-elYJRdeHrxRVF9

**Comment by zhDmitry** [comment]
hi, i guess it's might be issue with plain antd styles not with this lib, can u check it ?

**Comment by RomaSto** [comment]
The solution was to add display: block; to ant-form-item-children in Select html
