### ISSUE TITLE
NumberField problem with css

### ISSUE THREAD

**Issue by Herbatek** [zhDmitry/redux-form-antd#43]
Hello, 
I added NumberField to my form and it looks like this:

![obraz](https://user-images.githubusercontent.com/22417518/45697555-58763400-bb66-11e8-86df-11283c389270.png)

Arrows are outside and the field looks square

**Comment by zhDmitry** [comment]
I guess your forgot to import antd css file

**Comment by Herbatek** [comment]
i use create-react-app and i used [official doc](https://ant.design/docs/react/use-with-create-react-app) to import css. TextArea and textfield looks good. Just have a problem with number field.

**Comment by Herbatek** [comment]
I am an idiot. It was my fault.
