### ISSUE TITLE
Not working validation for Checkbox Field

### ISSUE THREAD

**Issue by jancama2** [zhDmitry/redux-form-antd#45]
### Current behavior
Since the Checkbox field uses `mapEvent` map for the props, only the `onChange` event is handled.
For some reason the blur event is not handled at all in the other browsers but Chrome. Chrome triggers  BLUR action on a form field in redux-form. The other browsers not.

### Expected behavior
Triggering `@@redux-form/BLUR` action `onBlur` so the validation is working.

### My solution
```
const mapping = customMap((mapProps, { input: { value, onChange, onBlur } }) => ({
    ...mapProps,
    checked: Boolean(value),
    onChange: e => {
        onChange(e.target.checked);
        onBlur(e.target.checked);
    },
}));

const CheckboxField = createComponent(Checkbox, mapping);
```
Here is my workaround but I don't know if it is correct. Any ideas?

Btw, the other thing is you have to use `checked` param since it is the thing triggering the change event.

**Comment by zhDmitry** [comment]
Yeah, it's seems to be a bug, but It rather bug of antd checkbox. For me it looks like workaround so I would suggest you just use code you provided in your project without merging it to this lib. For now I'm not working with antd so I don't have enough time to investigate with this issue. But if you can check if onBlur works fine with regular antd fields then we can transfer this issue to rc-checkbox

**Comment by jancama2** [comment]
Well, in the end the same problem is kinda in CheckboxGroupField too, it fails every time `onBlur` handler is called. The solution for the both CheckboxField and ChechboxField is to call the handler without inserting the event:
```
return {
        ...mapProps,
        onChange,
        onFocus: () => {
            onFocus();
        },
        onBlur: () => {
            onBlur();
        },
        value,
    };
``` 
Could help those who are having the same problems.
