### ISSUE TITLE
SelectField giving errors

### ISSUE THREAD

**Issue by johhansantana** [zhDmitry/redux-form-antd#7]
I'm getting a weird error

My code is the following:
```jsx
<Field
    label={'Categorías'}
    name="categories"
    component={SelectField}
    mode="multiple"
    placeholder={'Categorías'}
    options={[
      {
        "label": "Apple",
        "value": "Apple"
      },
      {
        "label": "Pear",
        "value": "Pear"
      },
      {
        "label": "Orange",
        "value": "Orange"
      }
    ]}
  />
```

`Error: must set key for <rc-animate> children`

![image](https://user-images.githubusercontent.com/9933887/30544084-53aa4c32-9c53-11e7-9d45-ced2dd9b7a52.png)

**Comment by zhDmitry** [comment]
@johhansantana  it seems that all is ok in story book when i set the same name and values. 
What can be different to usage in my storybook ?

**Comment by johhansantana** [comment]
hi @zhDmitry sorry I haven't replied back, we just passed through hurricane Maria here.

Could you give me an example of a working `SelectField`?

**Comment by zhDmitry** [comment]
@johhansantana [this](https://zhdmitry.github.io/redux-form-antd/?knob-labelCol=%7B%22span%22%3A24%2C%22offset%22%3A0%7D&knob-wrapperCol=%7B%22span%22%3A24%2C%22offset%22%3A0%7D&knob-options=%5B%7B%22label%22%3A%22Apple%22%2C%22value%22%3A%22Apple%22%7D%2C%7B%22label%22%3A%22Pear%22%2C%22value%22%3A%22Pear%22%7D%2C%7B%22label%22%3A%22Orange%22%2C%22value%22%3A%22Orange%22%7D%5D&knob-autosize=%7B%22minRows%22%3A2%2C%22maxRows%22%3A6%7D&knob-addonBefore=&knob-colon=true&knob-suffix=&knob-prefix=&knob-tokenSeparators=%2C&knob-type=text&knob-addonAfter=&knob-notFoundContent=not%20found&knob-size=default&knob-mode=multiple&knob-allowClear=false&knob-Placeholder=placeholder&knob-Label=label&selectedKind=TextField&selectedStory=Select%20Field&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by johhansantana** [comment]
I've tried using regular select field like this:
```jsx
const renderSelect2 = (field) => (
  <FormItem
    label={field.label}
    hasFeedback
  >
    <Select
      onChange={(event) => field.input.onChange(event)}
      placeholder={field.placeholder}
      mode={'multiple'}
    >
      {field.children}
    </Select>
  </FormItem>
)
```

and calling it like this:
```jsx
<Field
  label={'Categorías'}
  name="categories"
  component={renderSelect2}
  placeholder={'Categorías'}
>
  {
    categories.map((category, index) => (
      <Option 
        value={category.id}
        key={index}
      >
        {category.name}
      </Option>
    ))
  }
</Field>
```

it works at beginning but as soon as I select an option the same error appears.
