### ISSUE TITLE
Not able to display placeholder for SelectField

### ISSUE THREAD

**Issue by JackGit** [zhDmitry/redux-form-antd#8]
`<Field component={SelectField} name="testField" options={[{label:'app',value:'app'}]} placeholder="myplaceholder" />` 
I can't make placeholder display. Can u help?

**Comment by JackGit** [comment]
Found the issue, it's issue of antd. Close this one
https://github.com/react-component/select/pull/91

**Comment by jstorm31** [comment]
I run into same problem, but couldn't find out a solution. Has it been solved in antd package?

**Comment by zhDmitry** [comment]
Have you tried do not put null as placeholder value ?

**Comment by jstorm31** [comment]
Yes, if I put a string into placeholder, it is added to DOM, but overriden by first selected value (why?):

```
<div class="ant-select-selection__rendered">
   <div unselectable="unselectable" class="ant-select-selection__placeholder" style="display: none; user-select: none;">Placeholder text</div>
   <div class="ant-select-selection-selected-value" title="John" style="display: block; opacity: 1;">John</div>
</div>
```

```
<Field
    name="contactId"
    label={texts.labels.person}
    component={SelectField}
    options={_.map(dispatchers, (item) => { return { label: item.name, value: item.id }; })}
    className="input--xl"
    placeholder="Placeholder text"
/>
```
