### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by wapgear** [zhDmitry/redux-form-antd#9]
It's not working with React 16. 
`invariant.js:42 Uncaught Error: Element ref was specified as a string (component) but no owner was set. You may have multiple copies of React loaded.`

**Comment by zhDmitry** [comment]
@wapgear do you want submit pull request for it ?

**Comment by zhDmitry** [comment]
Check out last commit. It should be fixed.

**Comment by papigers** [comment]
Any reason this isn't published on npm?
